### ISSUE TITLE
Suspicious metrics evaluation

### ISSUE THREAD

**Issue by dupeljan** [antonior92/automatic-ecg-diagnosis#9]
Hi there!

I'm watching your model evaluation code and have found suspicious line of code:
https://github.com/antonior92/automatic-ecg-diagnosis/blob/master/generate_figures_and_tables.py#L120

Here you choose optimal threshold values by true labels value. Is it fair to choose hyperparameters each time you evaluate  your model? If you would use constant threshold values for each evaluation your final metrics are changed somehow.

**Comment by antonior92** [comment]
Hi Dupeljan. Thank you for pointing it.

I agree that the code [here](https://github.com/antonior92/automatic-ecg-diagnosis/blob/16dbb166a83b88e2e7fba314c8082011462153a8/generate_figures_and_tables.py#L28) is misleading. At the paper, we do it at the validation.

I tough to include the `get_optimal_precision_recall` function somewhere as a use case. But since the validation is not openly available, I tried to give examples that could actually be used.  At the moment, it sounded fair to do it as an illustration. Anyway, I agree that leads to more confusion (see #4 for another take on it)... 

It was possible to do that is because the obtained result is very similar in the two cases. Mostly because, as you can see in the precision-recall curve:
![precision-recall](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-15432-4/MediaObjects/41467_2020_15432_Fig2_HTML.png?as=webp)
there are some relatively large plateaus. Anyway, I see now that this only leads to confusion... I will fix it...
